# Generated by Django 5.0.4 on 2024-04-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_needs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtcs',
            new_name='Produtc',
        ),
    ]
