# Generated by Django 5.0.4 on 2024-04-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_needs', '0003_rename_produtc_product'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appearence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
