# Generated by Django 5.0.4 on 2024-05-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica_needs', '0004_product_appearence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
